sudo: required

services:
  - docker

language: generic

before_install:
  - docker-compose build
  - docker-compose up -d

before_script:
  - pip install requests
  - pip install pytest

script:
  - docker ps | grep -qw apiexplorer
  - docker ps | grep -qw apiexplorer_nginx
  - pytest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
