sudo: required

services:
  - docker

language: python

before_deploy:
  - docker login -u "DOCKER_USER" -p "DOCKER_PASSWORD"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
