version: '2'
 
services:
 gunicorn:
   restart: always
   build: ./gunicorn
   image: tidr/apiexplorer
   volumes:
     - ./gunicorn:/opt/apiexplorer
   command: python3 run.py
 
 nginx:
   restart: always
   build: ./nginx
   image: tidr/apiexplorer
   ports:
     - "443:443"
   volumes_from:
     - gunicorn
   depends_on:
     - gunicorn
