version: '3'

services:

  nginx:
    restart: always
    build: ./nginx
    image: tidr/apiexplorer_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./gunicorn:/opt/apiexplorer
    depends_on:
      - apiexplorer

  apiexplorer:
    restart: always
    build: ./gunicorn
    image: tidr/apiexplorer
    volumes:
      - ./gunicorn:/opt/apiexplorer
    command: python3.6 run.py

volumes:
  gunicorn: