version: "3.4"

services:

  nginx:
    restart: always
    build: ./nginx
    image: tidr/apiexplorer_nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - apiexplorer

  apiexplorer:
    restart: always
    build: ./gunicorn
    image: tidr/apiexplorer
    volumes:
      - type: volume
        source: gunicorn
        target: /opt/apiexplorer
        volume:
          nocopy: true
      - type: bind
        source: ./
        target: /opt/apiexplorer/app/db
    command: python3.6 run.py -p

volumes:
  gunicorn: