version: '2'
 
services:
 gunicorn:
   restart: always
   build: ./gunicorn
   image: tidr/apiexplorer/gunicorn:v1
   volumes:
     - ./gunicorn:/opt/apiexplorer
   command: python3.6 run.py

 nginx:
   restart: always
   build: ./nginx
   image: tidr/apiexplorer/nginx:v1
   ports:
     - "443:443"
   volumes_from:
     - gunicorn
   depends_on:
     - gunicorn
